First phase of high-availability objects.
PaloAltoNetworks/pango pull request #45
Opened 2021-01-01 17:02 UTC by kevinsteves

Includes all config for active passive, HA interfaces and link
monitoring groups.

TODO: active active, cluster, path monitoring groups.

2021-01-06 18:11 UTC, shinmog requested changes
Nice work!

I noticed that there are no unit tests with either of these.  Unit tests are there to help make sure that your marshaling / unmarshaling and `Copy()` are working properly.  Especially with only one version on each of these namespaces, the unit tests aren't that bad.  You don't have to go ham on unit tests like I've done for some of the namespaces, but I'd like to see a few unit tests for these namespaces as well.  You can use netw/routing/protocol/bgp as the basis for the ha unit tests:  just copy "fw_test.go" over (updating calls to `Get()` and `Set()` as appropriate), and copy "testdata_test.go" over (updating the Config as appropriate).

2021-01-06 18:11 UTC, shinmog commented on dev/ha/config.go
> +}
Please ditch this anonymous struct; just put the params in the structs that need them.

2021-01-07 00:03 UTC, kevinsteves commented
Address changes requested.

2021-01-07 05:09 UTC, shinmog approved these changes
Ok cool :)

The HA object is huge, and it's much easier in practice to have your unittests only do certain chunks of config in each test.  This is because if there is a bug, looking at a huge struct dump comparing what was sent with what was expected makes it very hard to see what the difference is.  But great work on this!

2021-01-07 05:09 UTC, merged